"""Plot tICA-transformed coordinates

msmbuilder autogenerated template version 2
created 2021-12-22T12:39:44.996746
please cite msmbuilder in any publications
"""

import matplotlib
matplotlib.use('Agg')
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

from msmbuilder.io import load_trajs, load_generic

import os, sys, getopt

verbose = False
dir_name = ""

# parse cmdline args in a C-like manner
try:
    opts, args = getopt.getopt(sys.argv[1:], "vd:")
except getopt.GetoptError as err:
    print(err)
    sys.exit(1)

for o, a in opts:
    if o == "-v":
        verbose = True
    elif o == "-d":
        dir_name = a

if dir_name != "":
    try:
        os.mkdir(dir_name)
    except:
        pass # ignore err due to existing dir
    os.chdir(dir_name)

sns.set_style('ticks')
colors = sns.color_palette()

## Load
tica = load_generic('tica.pickl')
meta, ttrajs = load_trajs('ttrajs')
txx = np.concatenate(list(ttrajs.values()))

## Heatmap
def plot_heatmap(ax):
    ax.hexbin(txx[:, 0], txx[:, 1],
              cmap=sns.cubehelix_palette(as_cmap=True),
              mincnt=1,
              bins='log'
              )
    ax.set_xlabel("tIC 1", fontsize=16)
    ax.set_ylabel("tIC 2", fontsize=16)


## Timescales
def plot_timescales(ax):
    timestep = meta['step_ps'].unique()
    assert len(timestep) == 1, timestep
    timestep = float(timestep[0])  # ps
    to_us = (
        (1.0 / 1000)  # ps -> ns
        * (1.0 / 1000)  # ns -> us
        * (timestep / 1)  # steps -> ps
    )
    ax.hlines(tica.timescales_ * to_us,
              0, 1,
              color=colors[0])
    ax.set_ylabel(r'Timescales / $\mathrm{\mu s}$', fontsize=18)
    ax.set_xticks([])
    ax.set_xlim((0, 1))


## Plot 1
fig, ax = plt.subplots(figsize=(7, 5))
plot_heatmap(ax)
fig.tight_layout()
fig.savefig('tica-heatmap.pdf')
# 

## Plot 2
fig, ax = plt.subplots(figsize=(3, 5))
plot_timescales(ax)
fig.tight_layout()
fig.savefig('tica-timescales.pdf')
# 